# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ubuntu-build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    env:
      CI: true
      working-directory: ./path/to/site-vitrine/prod

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build
      working-directory:  ${{env.working-directory}}
    - run: git remote add dev-vitrine path/to/site-vitrine/dev
    - run: git fetch dev-vitrine
    - run: git merge --allow-unrelated-histories dev-vitrine/master
    - run: git remote remove dev-vitrine
